### ISSUE TITLE
Can't complie de4dot

### ISSUE THREAD

**Issue by hoangcuongflp** [0xd4d/de4dot#144]
I have error when complie like this:
------ Build started: Project: dnlib, Configuration: Release Any CPU ------
Build started 3/25/2018 12:42:58 AM.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.CSharp.targets(316,9): error CS1617: Invalid option '4' for /langversion; must be ISO-1, ISO-2, 3 or Default

Build FAILED.

Time Elapsed 00:00:00.03
------ Build started: Project: Test.Rename.Dll, Configuration: Release Any CPU ------
Build started 3/25/2018 12:42:59 AM.
CopyFilesToOutputDirectory:
  Test.Rename.Dll -> C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\Test.Rename.Dll.dll

Build succeeded.

Time Elapsed 00:00:00.01
------ Build started: Project: de4dot.blocks, Configuration: Release Any CPU ------
error CS0006: Metadata file 'C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll' could not be found

Compile complete -- 1 errors, 0 warnings
Build started 3/25/2018 12:42:59 AM.
ResolveAssemblyReferences:
  Primary reference "dnlib".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
CoreCompile:
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE /errorendlocation /preferreduilang:en-US /highentropyva- /reference:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll /debug:pdbonly /filealign:512 /keyfile:..\de4dot.snk /optimize+ /out:obj\Release\de4dot.blocks.dll /target:library /warnaserror+ /utf8output BaseBlock.cs Block.cs Blocks.cs BlocksSorter.cs cflow\BlockCflowDeobfuscator.cs cflow\BlockDeobfuscator.cs cflow\BlocksCflowDeobfuscator.cs cflow\BranchEmulator.cs cflow\CachedCflowDeobfuscator.cs cflow\CflowDeobfuscator.cs cflow\CflowUtils.cs cflow\ConstantsFolder.cs cflow\DeadCodeRemover.cs cflow\DeadStoreRemover.cs cflow\DupBlockDeobfuscator.cs cflow\IBlocksDeobfuscator.cs cflow\ICflowDeobfuscator.cs cflow\InstructionEmulator.cs cflow\Int32Value.cs cflow\Int64Value.cs cflow\MethodCallInliner.cs cflow\MethodCallInlinerBase.cs cflow\Real8Value.cs cflow\StLdlocFixer.cs cflow\SwitchCflowDeobfuscator.cs cflow\Value.cs cflow\ValueStack.cs CodeGenerator.cs DeadBlocksRemover.cs DotNetUtils.cs DumpedMethod.cs DumpedMethods.cs FilterHandlerBlock.cs ForwardScanOrder.cs GenericArgsSubstitutor.cs HandlerBlock.cs Instr.cs InstructionListParser.cs MemberDefDict.cs MethodBlocks.cs Properties\AssemblyInfo.cs ScopeBlock.cs StackTracePatcher.cs TryBlock.cs TryHandlerBlock.cs Utils.cs

Build FAILED.

Time Elapsed 00:00:00.01
------ Build started: Project: Test.Rename, Configuration: Release Any CPU ------
Build started 3/25/2018 12:42:59 AM.
CopyFilesToOutputDirectory:
  Test.Rename -> C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\Test.Rename.exe

Build succeeded.

Time Elapsed 00:00:00.09
------ Build started: Project: de4dot.mdecrypt, Configuration: Release Any CPU ------
error CS0006: Metadata file 'C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll' could not be found
error CS0006: Metadata file 'C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll' could not be found

Compile complete -- 2 errors, 0 warnings
Build started 3/25/2018 12:42:59 AM.
ResolveAssemblyReferences:
  Primary reference "de4dot.blocks".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
  Primary reference "dnlib".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
CoreCompile:
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /unsafe+ /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE /errorendlocation /preferreduilang:en-US /highentropyva- /reference:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll /reference:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll /debug:pdbonly /filealign:512 /keyfile:..\de4dot.snk /optimize+ /out:obj\Release\de4dot.mdecrypt.dll /target:library /warnaserror+ /utf8output DecryptMethodsInfo.cs DynamicMethodsDecrypter.cs NativeCodeGenerator.cs Properties\AssemblyInfo.cs

Build FAILED.

Time Elapsed 00:00:00.01
------ Build started: Project: AssemblyData, Configuration: Release Any CPU ------
error CS0006: Metadata file 'C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll' could not be found
error CS0006: Metadata file 'C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.mdecrypt.dll' could not be found
error CS0006: Metadata file 'C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll' could not be found

Compile complete -- 3 errors, 0 warnings
Build started 3/25/2018 12:42:59 AM.
ResolveAssemblyReferences:
  Primary reference "de4dot.blocks".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
  Primary reference "de4dot.mdecrypt".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.mdecrypt.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.mdecrypt.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.mdecrypt.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
  Primary reference "dnlib".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
CoreCompile:
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:AnyCPU /errorreport:prompt /warn:4 /define:TRACE /errorendlocation /preferreduilang:en-US /highentropyva- /reference:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll /reference:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.mdecrypt.dll /reference:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Runtime.Remoting.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Xml.dll /debug:pdbonly /filealign:512 /keyfile:..\de4dot.snk /optimize+ /out:obj\Release\AssemblyData.dll /target:library /warnaserror+ /utf8output AssemblyResolver.cs AssemblyServer.cs AssemblyService.cs DelegateStringDecrypter.cs EmuStringDecrypter.cs GenericService.cs IAssemblyService.cs IGenericService.cs IMethodDecrypterService.cs IStringDecrypter.cs IStringDecrypterService.cs IUserGenericService.cs MethodDecrypterService.cs methodsrewriter\AssemblyResolver.cs methodsrewriter\CodeGenerator.cs methodsrewriter\IMethodsRewriter.cs methodsrewriter\MethodsRewriter.cs methodsrewriter\MField.cs methodsrewriter\MMethod.cs methodsrewriter\MModule.cs methodsrewriter\MType.cs methodsrewriter\Operand.cs methodsrewriter\Resolver.cs methodsrewriter\ResolverUtils.cs methodsrewriter\TypeInstanceResolver.cs methodsrewriter\TypeResolver.cs Properties\AssemblyInfo.cs SimpleData.cs StringDecrypterService.cs Utils.cs

Build FAILED.

Time Elapsed 00:00:00.01
------ Build started: Project: de4dot.code, Configuration: Release Any CPU ------
Build started 3/25/2018 12:42:59 AM.
ResolveAssemblyReferences:
  Primary reference "AssemblyData".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\AssemblyData.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\AssemblyData.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\AssemblyData.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
  Primary reference "de4dot.blocks".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
  Primary reference "de4dot.mdecrypt".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.mdecrypt.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.mdecrypt.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.mdecrypt.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
  Primary reference "dnlib".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
CoreResGen:
  C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\ResGen.exe /useSourcePath /r:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\AssemblyData.dll /r:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll /r:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.mdecrypt.dll /r:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll /r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll /r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll /r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Drawing.dll /r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Runtime.Remoting.dll /r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Xml.dll /compile deobfuscators\Agile_NET\vm\v2\CsvmResources.resx,obj\Release\de4dot.code.deobfuscators.Agile_NET.vm.v2.CsvmResources.resources 
ResGen : error RG0000: Could not load referenced assembly "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\AssemblyData.dll".  Caught a FileNotFoundException saying "Could not load file or assembly 'C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\AssemblyData.dll' or one of its dependencies. The system cannot find the file specified.".
  1 error(s).

Build FAILED.

Time Elapsed 00:00:00.28
------ Build started: Project: de4dot.cui, Configuration: Release Any CPU ------
error CS0006: Metadata file 'C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.code.dll' could not be found
error CS0006: Metadata file 'C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll' could not be found
error CS0006: Metadata file 'C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll' could not be found

Compile complete -- 3 errors, 0 warnings
Build started 3/25/2018 12:42:59 AM.
ResolveAssemblyReferences:
  Primary reference "de4dot.blocks".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
  Primary reference "de4dot.code".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.code.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.code.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.code.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
  Primary reference "dnlib".
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll" does not exist.
      Could not find dependent files. Expected file "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll" does not exist.
      Resolved file path is "C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll".
      Reference found at search path location "".
      The ImageRuntimeVersion for this reference is "".
CoreCompile:
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:AnyCPU /errorreport:prompt /warn:4 /define:TRACE /errorendlocation /preferreduilang:en-US /highentropyva- /reference:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.blocks.dll /reference:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\Release\bin\de4dot.code.dll /reference:C:\Users\hoang\Downloads\de4dot\de4dot-3.1.41592\dnlib\Release\bin\dnlib.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll /debug:pdbonly /filealign:512 /keyfile:..\de4dot.snk /optimize+ /out:obj\Release\de4dot.cui.dll /target:library /warnaserror+ /utf8output CommandLineParser.cs FilesDeobfuscator.cs Program.cs Properties\AssemblyInfo.cs

Build FAILED.

Time Elapsed 00:00:00.04
------ Skipped Build: Project: AssemblyServer-CLR20-x64, Configuration: Release x86 ------
Project not selected to build for this solution configuration 
------ Skipped Build: Project: AssemblyServer-CLR40, Configuration: Release x86 ------
Project not selected to build for this solution configuration 
------ Skipped Build: Project: AssemblyServer-x64, Configuration: Release x86 ------
Project not selected to build for this solution configuration 
------ Skipped Build: Project: AssemblyServer, Configuration: Release x86 ------
Project not selected to build for this solution configuration 
------ Skipped Build: Project: de4dot-x64, Configuration: Release x86 ------
Project not selected to build for this solution configuration 
------ Skipped Build: Project: de4dot, Configuration: Release x86 ------
Project not selected to build for this solution configuration 
------ Skipped Build: Project: AssemblyServer-CLR40-x64, Configuration: Release x86 ------
Project not selected to build for this solution configuration 
------ Skipped Build: Project: AssemblyServer-CLR20, Configuration: Release x86 ------
Project not selected to build for this solution configuration 
------ Skipped Build: Project: Examples, Configuration: Release x86 ------
Project not selected to build for this solution configuration 
========== Build: 2 succeeded or up-to-date, 6 failed, 9 skipped ==========

**Comment by hoangcuongflp** [comment]
I'm really add dnlib project

**Comment by 0xd4d** [comment]
Use latest version of Visual Studio.

**Comment by 0xd4d** [comment]
Or get binaries from the build server https://ci.appveyor.com/project/0xd4d/de4dot/build/artifacts
