### ISSUE TITLE
Couldn't find example file

### ISSUE THREAD

**Issue by CoaBro** [0xd4d/de4dot#145]
C:\Users\"USER"\Desktop\de4dot-master\dnlib\Examples\Examples.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\"USER"\Desktop\de4dot-master\dnlib\Examples\Examples.csproj'.  C:\Users\"USER"\Desktop\de4dot-master\dnlib\Examples\Examples.csproj

**Comment by HoLLy-HaCKeR** [comment]
https://github.com/0xd4d/de4dot/wiki/Compiling-de4dot

**Comment by 0xd4d** [comment]
Unless you want to update it, you can just download the binaries from the build server: https://ci.appveyor.com/project/0xd4d/de4dot/branch/master/artifacts
