### ISSUE TITLE
VS 2017 doesnt compile?

### ISSUE THREAD

**Issue by tazotodua** [0xd4d/de4dot#149]
I tried google and nowhere found any instructions. I get error when compiling with VS 2017:

https://i.imgur.com/ywOdd54.png

(and 100's of similar errors for non-declared types)
Is there anywhere step-by-step instruction how to compile de4dot?

**Comment by riQQ** [comment]
https://github.com/0xd4d/de4dot/wiki/Compiling-de4dot
