### ISSUE TITLE
Method name changed

### ISSUE THREAD

**Issue by IranDeveloper** [0xd4d/de4dot#165]
i unpack my exe app but method name changed

for example : 

private static void SelectAllText(object sender, RoutedEventArgs e)
    {
      var textbox = e.OriginalSource as TextBox;
      if (textbox != null)
               textbox .SelectAll();
    }

change to :

private static void smethod_2(object sender, RoutedEventArgs e)
    {
      TextBox originalSource = e.OriginalSource as TextBox;
      if (originalSource == null)
        return;
      originalSource.SelectAll();
    }

how i got original name.?
thanks.♥

**Comment by Inojin** [comment]
You can't unless they are stored somewhere in the exe

**Comment by XenocodeRCE** [comment]
@IranDeveloper here : https://github.com/0xd4d/de4dot#disabling-symbol-renaming

```
de4dot.exe --dont-rename your_file.exe
```


won't produce those strange names. As far as original name, you cannot restore them.
