### ISSUE TITLE
WARNING: The file isn't a .NET PE file: F:\

### ISSUE THREAD

**Issue by Felix-Wong** [0xd4d/de4dot#170]
WARNING: The file isn't a .NET PE file: F:\

**Comment by UlyssesWu** [comment]
You should provide more information or nobody can figure out what happened.

For now I guess you are trying to open a shell packed file, or your file is not a .NET assembly.

**Comment by UlyssesWu** [comment]
How did you know your exe file is a **.NET** assembly rather than a Win32 exe file? 
Did you try dumping the .NET assembly when the program is running?

**Comment by Felix-Wong** [comment]
I'm not sure about the program
The result detected with PEID is:
Microsoft Visual C++ 6.0 DLL [Overlay]
Win32 GUI

**Comment by UlyssesWu** [comment]
I'm afraid your program is not written by .NET languages. de4dot is made for .NET (please read README.md). So maybe you should try other tools. 
However, if you confirmed it's using CLR when running, you may try dumping .NET assemblies from the program process.

**Comment by Felix-Wong** [comment]
How to judge unknown program?

**Comment by 0xd4d** [comment]
Just like @UlyssesWu says, and what de4dot printed to the console, it's not a supported file because it's not .NET.
