### ISSUE TITLE
Unpack .Net Reactor without error but Code still messy

### ISSUE THREAD

**Issue by Thiencau20** [0xd4d/de4dot#174]
Hello, I use latest de4dot to unpack and everything is fine ! But Open with dnspy , code still messy ! 
How to full unpack Mr . 0xd4d ? Thanks !
The screenshot open with Dnspy !
http://prntscr.com/kreh9r
![screenshot_1](https://user-images.githubusercontent.com/7241067/45173924-b97f3d00-b233-11e8-8f92-29bf59c721c9.png)

**Comment by computerline1z** [comment]
Could you provide sample or more info, the picture above only show class rename, that normal deobfuscate process.
