### ISSUE TITLE
Could not find all arguments to method system.boolean mI2WJBci3blusMeu4Br.efUAFnzbSivgVRB3Kv??

### ISSUE THREAD

**Issue by ncrispi** [0xd4d/de4dot#177]
When I try to run this on an exe file I get : Could not find all arguments to method system.boolean mI2WJBci3blusMeu4Br.efUAFnzbSivgVRB3Kv??

When I try to open the project in Visual Basic I cannot run it as there are errors from what look like still obfuscated code (I get 300+ errors total)

**Comment by ddf420** [comment]
It looks like .NET Reactor obfuscated binaries with high level control flow. Mind putting the verbose log of de4dot
