### ISSUE TITLE
 Agile.NET  ERROR: Hmmmm... something didn't work. Try the latest version.  

### ISSUE THREAD

**Issue by leon4770** [0xd4d/de4dot#178]
de4dot v3.1.41592.3405 Copyright (C) 2011-2015 de4dot@gmail.com
Latest version and source code: https://github.com/0xd4d/de4dot

  1: Unknown
130: Agile.NET
  0: Babel .NET
  0: CodeFort
  0: CodeVeil
  0: CodeWall
Deobfuscating control flow: System.Void <Module>::.cctor() (06000001)
Deobfuscating control flow: System.Void <AgileDotNetRT>::Initialize() (0600021E)
Deobfuscating control flow: System.Void <AgileDotNetRT>::PostInitialize() (0600021F)
Deobfuscating control flow: System.Void Fjw=.GDw=::rrr() (06000222)
  0: Confuser
  0: Crypto Obfuscator
Deobfuscating control flow: System.Void <Module>::.cctor() (06000001)
  0: DeepSea
  0: Dotfuscator
  0: .NET Reactor 3.x
  0: .NET Reactor 4.x
  0: Eazfuscator.NET
  0: Goliath.NET
  0: ILProtector
  0: MaxtoCode
  0: MPRESS
  0: Rummage
  0: Skater .NET
  0: SmartAssembly
  0: Spices.Net
  0: Xenocode
Detected Agile.NET (G:\taobao软件\Root.dll)
Cleaning G:\taobao软件\Root.dll
Using dynamic method decryption
ERROR:
ERROR:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Stack trace:
ERROR:
ERROR: Server stack trace:
ERROR:    在 System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
ERROR:    在 System.Runtime.Remoting.Channels.Ipc.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 size)
ERROR:    在 System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
ERROR:    在 System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
ERROR:    在 System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
ERROR:    在 System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
ERROR:    在 System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
ERROR:    在 System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
ERROR:    在 System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
ERROR:    在 System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
ERROR:
ERROR: Exception rethrown at [0]:
ERROR:    在 de4dot.code.deobfuscators.MethodsDecrypter.Decrypt(ServerClrVersion serverVersion, String filename, Byte[] moduleCctorBytes) 位置 E:\de4dot-master\de4dot.code\deobfuscators\MethodsDecrypter.cs:行号 45
ERROR:    在 de4dot.code.deobfuscators.MethodsDecrypter.Decrypt(ModuleDef module, Byte[] moduleCctorBytes) 位置 E:\de4dot-master\de4dot.code\deobfuscators\MethodsDecrypter.cs:行号 31
ERROR:    在 de4dot.code.deobfuscators.Agile_NET.MethodsDecrypter.Decrypt(MyPEImage peImage, ModuleDefMD module, CliSecureRtType csRtType, DumpedMethods& dumpedMethods) 位置 E:\de4dot-master\de4dot.code\deobfuscators\Agile_NET\MethodsDecrypter.cs:行号 453
ERROR:    在 de4dot.code.deobfuscators.Agile_NET.Deobfuscator.GetDecryptedModule(Int32 count, Byte[]& newFileData, DumpedMethods& dumpedMethods) 位置 E:\de4dot-master\de4dot.code\deobfuscators\Agile_NET\Deobfuscator.cs:行号 215
ERROR:    在 de4dot.code.ObfuscatedFile.Deobfuscate() 位置 E:\de4dot-master\de4dot.code\ObfuscatedFile.cs:行号 394
ERROR:    在 de4dot.cui.FilesDeobfuscator.DeobfuscateAllFiles(IEnumerable`1 allFiles) 位置 E:\de4dot-master\de4dot.cui\FilesDeobfuscator.cs:行号 373
ERROR:    在 de4dot.cui.FilesDeobfuscator.DeobfuscateAll() 位置 E:\de4dot-master\de4dot.cui\FilesDeobfuscator.cs:行号 134
ERROR:    在 de4dot.cui.FilesDeobfuscator.DoIt() 位置 E:\de4dot-master\de4dot.cui\FilesDeobfuscator.cs:行号 91
ERROR:    在 de4dot.cui.Program.Main(String[] args) 位置 E:\de4dot-master\de4dot.cui\Program.cs:行号 117
ERROR:
ERROR:
ERROR: Caught an exception:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Message:
ERROR:   从 IPC 端口读取时失败: 管道已结束。
ERROR:
ERROR: Type:
ERROR:   System.Runtime.Remoting.RemotingException
ERROR: ------------------------------------------------------------------------------
ERROR:
ERROR: Try the latest version!

**Comment by leon4770** [comment]
[Root.zip](https://github.com/0xd4d/de4dot/files/2460546/Root.zip)

attached is the example file, please help.

**Comment by 0xd4d** [comment]
#155
