### ISSUE TITLE
Decrypt1() params input in MaxtoCode MethodsDecrypter.cs?

### ISSUE THREAD

**Issue by Tianjiao** [0xd4d/de4dot#179]
Hello,

I'm working on the de4dot code for MaxtoCode, can decrypt resource and string, but stuck at the methods decrypter.

In [/de4dot.code/deobfuscators/MaxtoCode/MethodsDecrypter.cs](https://github.com/0xd4d/de4dot/blob/master/de4dot.code/deobfuscators/MaxtoCode/MethodsDecrypter.cs)

Definition:
`byte[] Decrypt1(byte[] encrypted, int keyStart, int keyReset, int keyEnd) {`
Apply in:
`byte[] Decrypt1_v2(byte[] encrypted) => Decrypt1(encrypted, 6, 6, 0x500);`
But how to get the "6" "6" "0x500" input? 

Definition:
`byte[] Decrypt2(byte[] encrypted, int offset) {`
Apply in:
`byte[] Decrypt2_v3(byte[] encrypted) => Decrypt2(encrypted, 0x00FA + 0x24);`
But how to get the added "0x24" input? 

Any hints on How to GET these manual param input?
If this issue is succesfully solved, I can pull a full PR then.

Thanks in advance.

**Comment by 0xd4d** [comment]
You get those by analyzing the native DLL file, they're different in each build it seems. AFAIK there's no easy way of doing it, but you could perhaps try to guess or write code to try to discover the values by trying every combination until it seems to have decrypted it.

**Comment by Tianjiao** [comment]
Thanks but could you give me some **code snippet**?

I agree with you that the native DLL file, namely MaxtoCode Runtime, is written in C++ and protected by VMprotect, so not easy to be analyzed.

However, trying the combination is not easy as well. The last line that I have to add is like this:

`decrypters.Add(new Decrypter(new DecryptFunc[] { Decrypt1_v1, Decrypt2_v1, Decrypt3_v6, Decrypt4_v1, Decrypt5, Decrypt6, Decrypt7, Decrypt8_v5, Decrypt9_v5, Decrypt10, Decrypt11_v1 }, new uint[] { 0x51413D68 }));`

But each decrypt method has about 10 variants, which means that I have to try (11)10 times at each build...

PS: I didn't mean to disturb you. I have heard some Chinese to have dumped the MaxtoCode protected file, but the unpacked file is still detected to be MaxtoCode by de4dot, and there seems to have some remains in the resource section..
Yes, the encrypted methods could be dumped or decrypted, de4dot chooses to decrypt the methods at large. So the point lies in how to get the decrypt parameters. There are few online resource about this so I ask you for help.

**Comment by 0xd4d** [comment]
There's no code snippet, you have to analyze the native DLL. That's what I did.
