### ISSUE TITLE
Can't build if reset to "Remove public, add static"

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/de4dot#183]
1. Open vs2017, open Team Explorer, Click 'Clone', enter: https://github.com/0xd4d/de4dot.git, Click the button 'Clone'
![f](https://user-images.githubusercontent.com/2529999/47265847-8a612880-d560-11e8-9bd0-a98da3014ae6.jpg)

2.Wait for finish, then open 'de4dot.netframework.sln' and press "F6" to build it ,succeed!

3. Reset Delete Changes (--hard) to: 'Remove public, add static'
![2](https://user-images.githubusercontent.com/2529999/47265883-5fc39f80-d561-11e8-8d30-4133cf2525cb.jpg)

4.Close vs2017 and open 'de4dot.sln', then update submodule
![3](https://user-images.githubusercontent.com/2529999/47265907-b7620b00-d561-11e8-8f1a-429546bda0ef.jpg)
vs2017 will report a error:
![4](https://user-images.githubusercontent.com/2529999/47265917-e4aeb900-d561-11e8-8069-dc8970dfd2cb.jpg)

5. Close vs2017 and open 'de4dot.sln again, press F6 to build it, failded:
![5](https://user-images.githubusercontent.com/2529999/47265934-37887080-d562-11e8-9cbc-f2e7fe66cc7f.jpg)

6. Pull incoming commits, close vs2017 and open 'de4dot.netframework.sln', this now 'Submodule Update' is disable:
![6](https://user-images.githubusercontent.com/2529999/47265997-b2ea2200-d562-11e8-97d3-e590ffa84883.jpg)
This time, I have already update to the lastest, but I can't build it also.

**Comment by 0xd4d** [comment]
Doesn't look like a de4dot problem.

**Comment by 0xd4d** [comment]
You can send a bug report to MS.
