### ISSUE TITLE
 .NET Reactor(4.8-4.9)[-] Unpacked problem

### ISSUE THREAD

**Issue by Anonymous-ghost** [0xd4d/de4dot#187]
![8](https://user-images.githubusercontent.com/42628190/47661724-8f634f00-dbd4-11e8-994e-2bc7d5cdaa02.png)
this program with .net reactor packed .use your tools to unpack .it works. but it has  a little problem。s
ome method or  arguments have obfuscator。can you update your tools  .or can you tell me how to upack this
.net Reactor not with this error which like the picture。thank you very much .your tools very good!!!

**Comment by Anonymous-ghost** [comment]
detail info
de4dot v3.1.41592.3405 Copyright (C) 2011-2015 de4dot@gmail.com
Latest version and source code: https://github.com/0xd4d/de4dot

Detected .NET Reactor (D:\搜狗高速下载\Ttest.exe)
Cleaning D:\搜狗高速下载\test.exe
WARNING: Could not find all arguments to method System.String kFxWVONWGHnTyJXuyf.jMe9CLmHhFDwGOotsA::LiZRYeqvwl(System.Int32) (06000A20), instr: IL_000F: ldarg
Renaming all obfuscated symbols
Saving D:\搜狗高速下载\test-cleaned.exe
Ignored 52 warnings/errors
Use -v/-vv option or set environment variable SHOWALLMESSAGES=1 to see all messages

**Comment by 0xd4d** [comment]
Dupe https://github.com/0xd4d/de4dot/issues/166
