### ISSUE TITLE
Deobfuscate unknown obfuscator?

### ISSUE THREAD

**Issue by m1m2m3mr** [0xd4d/de4dot#189]
I know there is no support but are anyone willing to update de4dot to support this exe sample? 
I wish I could update it myself but I don't have enough C# skills to do it. I don't know what forum I should look for now since most reverse enginner forum I found like URET are shut down already.

[Dev.zip](https://github.com/0xd4d/de4dot/files/2544154/Dev.zip)

**Comment by 0xd4d** [comment]
This is for issues not unpacking requests.
