### ISSUE TITLE
Issue with funtions after deobfuscate Crypto Obfuscator

### ISSUE THREAD

**Issue by stosea** [0xd4d/de4dot#190]
Hi all, the file cleaned is show function which refer to delegate class and no content to read, do any one meet same problem ?
![image](https://user-images.githubusercontent.com/44799333/48050883-f33dd700-e1d5-11e8-8496-63a0150bd7e8.png)

**Comment by 0xd4d** [comment]
Let's keep all Crypto Obfuscator problems in one issue: https://github.com/0xd4d/de4dot/issues/188
