### ISSUE TITLE
Eazfuscator deobfuscation causing memory leak on de4dot-x64.exe

### ISSUE THREAD

**Issue by ghost** [0xd4d/de4dot#191]
Yeah I just discovered the memory leak issue on de4dot-x64.exe while deobfuscating Eazfuscator and it gets stuck for infinite
de4dot.exe which is x86 version is working fine.

![image](https://user-images.githubusercontent.com/20967118/48278584-3dc98880-e44e-11e8-8834-7882fbaa8a27.png)

![image](https://user-images.githubusercontent.com/20967118/48278521-0bb82680-e44e-11e8-803e-76ce000cae0c.png)

**Comment by 0xd4d** [comment]
Can't repro without a sample and don't expect to get one since the user deleted his/her account.
